name: service_shop
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.3

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  flutter_secure_storage: ^9.2.2
  get_it: ^8.0.3
  mask_text_input_formatter: ^2.9.0
  dio: ^5.8.0+1
  equatable: ^2.0.7
  cached_network_image: ^3.4.1
  flutter_svg: ^2.2.1
  url_launcher: ^6.1.10
  shared_preferences: ^2.3.0
  image_picker: ^1.2.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/logo/
    - assets/img/